# Copyright 2016 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

version: 1.0.{build}-{branch}

shallow_clone: true

branches:
  only:
    - master
    - develop

platform:
  - x64

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARGS: --toolset=clang-win address-model=32,64
      CXXSTD: 11,14,17,2a

install:
  - cd ..
  - git clone -b %APPVEYOR_REPO_BRANCH% --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - xcopy /s /e /q %APPVEYOR_BUILD_FOLDER% libs\config
  - git submodule update --init --jobs 7 --
      tools/build
      tools/boost_install
      libs/headers
      libs/detail
      libs/core
      libs/assert
      libs/type_traits
  - bootstrap
  - b2 headers
  
build: off

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

test_script:
  - cd libs\config\test
  - ..\..\..\b2 print_config_info %ARGS% cxxstd=%CXXSTD%
  - ..\..\..\b2 -j3 %ARGS% cxxstd=%CXXSTD%
